Remove support for checking types
In ROS2, it is no longer possible to set the data field of ROS numeric
types (Float32, Float64, int, ...) to numpy types, because the setter
checks that it's a python primitive type. For example:

    >>> std_msgs.msg.Float32(data=np.float32(1.23))
    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-22-058863cbc4e3> in <module>
    ----> 1 std_msgs.msg.Float32(data=np.float32(1.23))

    /opt/ros/galactic/lib/python3.8/site-packages/std_msgs/msg/_float32.py in __init__(self, **kwargs)
         69             'Invalid arguments passed to constructor: %s' % \
         70             ', '.join(sorted(k for k in kwargs.keys() if '_' + k not in self.__slots__))
    ---> 71         self.data = kwargs.get('data', float())
         72
         73     def __repr__(self):

    /opt/ros/galactic/lib/python3.8/site-packages/std_msgs/msg/_float32.py in data(self, value)
        117     def data(self, value):
        118         if __debug__:
    --> 119             assert \
        120                 isinstance(value, float), \
        121                 "The 'data' field must be of type 'float'"

    AssertionError: The 'data' field must be of type 'float'